kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000 # app
        hostPort: 80
        protocol: TCP
      - containerPort: 30001 # (not used)
        hostPort: 443
        protocol: TCP
      - containerPort: 30002 # status
        hostPort: 15021
        protocol: TCP
      - containerPort: 30003 # kiali
        hostPort: 20001
        protocol: TCP
      - containerPort: 30004 # prometheus
        hostPort: 9090
        protocol: TCP
      - containerPort: 30005 # grafana
        hostPort: 3000
        protocol: TCP
