kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000 # app
        hostPort: 80
        protocol: TCP
      - containerPort: 30001 # status
        hostPort: 15021
        protocol: TCP
      - containerPort: 30002 # kiali
        hostPort: 20001
        protocol: TCP
      - containerPort: 30003 # prometheus
        hostPort: 9090
        protocol: TCP
      - containerPort: 30004 # grafana
        hostPort: 3000
        protocol: TCP
      - containerPort: 30005 # admin-server
        hostPort: 8081
        protocol: TCP
