grafana:
  service:
    port: 3000
  sidecar:
    datasources:
      - name: Prometheus
        type: prometheus
        isDefault: true
        url: http://prometheus-kube-prometheus-prometheus:9090/
        access: proxy
