apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: pet-clinic
    service: api-gateway
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api-gateway
        version: 1.0.0
    spec:
      automountServiceAccountToken: false
      containers:
        - name: api-gateway
          image: api-gateway:latest
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1001
            runAsGroup: 2001
