server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: customers-service
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql
  sleuth:
    sampler:
      probability: 1.0
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  boot:
    admin:
      client:
        url: http://admin-server:8081

management:
  security:
    enabled: false
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
