apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-metrics
  namespace: prometheus
  labels:
    release: "prometheus"
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
      targetPort: 8080
      interval: 30s
  namespaceSelector:
    matchNames:
      - pet-clinic
  selector:
    matchLabels:
      service: api-gateway
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customers-service-metrics
  namespace: prometheus
  labels:
    release: "prometheus"
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
      targetPort: 8082
      interval: 30s
  namespaceSelector:
    matchNames:
      - pet-clinic
  selector:
    matchLabels:
      service: customers-service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: visits-service-metrics
  namespace: prometheus
  labels:
    release: "prometheus"
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
      targetPort: 8084
      interval: 30s
  namespaceSelector:
    matchNames:
      - pet-clinic
  selector:
    matchLabels:
      service: visits-service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vets-service-metrics
  namespace: prometheus
  labels:
    release: "prometheus"
spec:
  endpoints:
    - port: http
      path: /actuator/prometheus
      targetPort: 8083
      interval: 30s
  namespaceSelector:
    matchNames:
      - pet-clinic
  selector:
    matchLabels:
      service: vets-service
